#!/bin/bash

#SBATCH --job-name=BERT    # Job name
#SBATCH --output=R-%x.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --error=R-%x.%j.err     # Error handling
#SBATCH --nodes=1                # Total number of nodes requested
#SBATCH --cpus-per-task=8        # Schedule 4 cores (includes hyperthreading)
#SBATCH --time=04:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --gres=gpu               # Schedule a GPU
#SBATCH --partition=brown    # Run on either the red or brown queue

#srun hostname

echo "Running on $(hostname):"

python3 BERT.py