#!/bin/bash

#SBATCH --job-name=GPT-2000    # Job name
#SBATCH --output=R-%x.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --error=R-%x.%j.err     # Error handling
#SBATCH --nodes=1                # Total number of nodes requested
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=12:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --gres=gpu               # Schedule a GPU
#SBATCH --partition=red    # Run on either the red or brown queue

#srun hostname

echo "Running on $(hostname):"
nvidia-smi

python3 sample.py
python3 sample.py
python3 sample.py
python3 sample.py
python3 sample.py
python3 sample.py
python3 sample.py
python3 sample.py
python3 sample.py
python3 sample.py
python3 sample.py