#!/bin/bash

#SBATCH --job-name=LR_train    # Job name
#SBATCH --output=R-%x.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --error=R-%x.%j.err     # Error handling
#SBATCH --nodes=1                # Total number of nodes requested
#SBATCH --cpus-per-task=32        # Schedule 4 cores (includes hyperthreading)
#SBATCH --time=02:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=red    # Run on either the red or brown queue

#srun hostname

echo "Running on $(hostname):"

pip3 install sklearn
python3 LR_train.py